# Author's name: Tharathorn Bunrattanasathian
# Student ID: 6110546011

version: "3.7"
services:
  # MySQL atm database backend
  atm-web-db:
    container_name: atm-web-db
    image: mysql:5.7.22
    environment:
      TZ: "Asia/Bangkok"
      MYSQL_DATABASE: "atm"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"
    volumes:
      - ./db/dump:/docker-entrypoint-initdb.d
      - ./db/mysql-datadir:/var/lib/mysql # Default MySQL data directory
      - ./db/config/custom.cnf:/etc/mysql/conf.d/custom.cnf # MySQL configuration file
    restart: unless-stopped
    networks:
      - atm-frontend

  # Maven-based frontend of ATM-Web: #1
  atm-web:
    container_name: atm-web
    build:
      context: atm-web/.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - atm-web-db
      - bankaccount-api
    networks:
      - atm-frontend

  # MySQL bank database backend
  atm-bank-db:
    container_name: atm-bank-db
    image: mysql:5.7.22
    environment:
      TZ: "Asia/Bangkok"
      MYSQL_DATABASE: "bank"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./bankaccount-api/db/dump:/docker-entrypoint-initdb.d
      - ./bankaccount-api/db/mysql-datadir:/var/lib/mysql # Default MySQL data directory
      - ./bankaccount-api/db/config/custom.cnf:/etc/mysql/conf.d/custom.cnf # MySQL configuration file
    restart: unless-stopped
    networks:
      - atm-backend

  # Maven-based backend of 'bankaccount-api': #2
  bankaccount-api:
    container_name: bankaccount-api
    build:
      context: bankaccount-api/.
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    depends_on:
      - atm-bank-db
    networks:
      - atm-frontend
      - atm-backend

networks:
  atm-frontend:
    name: atm-frontend
    driver: bridge
  atm-backend:
    name: atm-backend
    driver: bridge
